# gov-os provenance · FRAME: systems-architecture · CORPUS-CLASS: test-tooling · OS-architecture
# vocabulary (path family, channel, socket/tunnel, shared memory, custody handover, sight,
# census). NON-GOAL: no offensive capability of any kind — every assertion proves I20 by function:
# every op reads as one of five families or as not-a-path, and the census REDS on an op that moves
# information across a boundary yet fits no family. Full declaration: SCOPE-STATEMENT.md.
"""P4 · I20 [GREEN] — THE FIVE-FAMILIES CENSUS.

Three proofs, one instrument (the sibling of the effect-order census):

  A1  COMPLETENESS + NO SIXTH WAY — every op registered on the gate is classified; the census is
      over the WHOLE registry (len(rows) == len(gate.ops)); the `sixth-way` set (a byte-mover
      fitting no family) is EMPTY; the `unknown` set (an op whose source will not read) is EMPTY.
  A2  READING MATCHES COMMITTED EVIDENCE — the live reading, rendered by the instrument's own
      `--md`, equals the committed evidence table byte-for-byte. A new op, or a changed reading,
      moves this table and REDS here until the evidence is regenerated (never hand-edited).
  A3  THE CHECK CAN FAIL (positive control) — a PLANTED op that moves bytes by a primitive
      belonging to no family reads as `sixth-way` and REDS; with the plant removed the census is
      green. Two controls: a STATIC one (classify a planted op directly) and a BEHAVIOURAL one (a
      planted op registered on a real gate, flagged by the census, then removed).
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
_ROOT = os.path.join(os.path.dirname(__file__), "..")
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from tools.conformance import five_families_census as P4          # noqa: E402


# ============================================================================================
# A1 — COMPLETENESS + NO SIXTH WAY over the whole shipped registry.
# ============================================================================================

class TestA1CompletenessNoSixthWay(unittest.TestCase):

    def setUp(self):
        self._s, self.gate, self.views = P4.build_full_kernel_for_census()
        self.rows = P4.census(self.gate, self.views)

    def test_census_is_over_the_whole_registry(self):
        # completeness = enumeration (P3): one row per registered op, no more, no fewer.
        self.assertEqual(len(self.rows), len(self.gate.ops))
        self.assertEqual(sorted(r["op"] for r in self.rows), sorted(self.gate.ops))

    def test_every_op_reads_as_one_family_or_not_a_path(self):
        allowed = set(P4.FIVE_FAMILIES) | {"not-a-path", "sixth-way", "unknown"}
        for r in self.rows:
            self.assertIn(r["class"], allowed, "%s got an out-of-vocabulary class %r" % (r["op"], r["class"]))
            self.assertTrue(r["reason"], "%s carries no reason — every reading is recorded" % r["op"])

    def test_no_sixth_way(self):
        # THE load-bearing invariant: no op moves information across a boundary while fitting no
        # family. A non-empty set is I20 refuted — a paper finding, never a silent family-widening.
        sw = P4.sixth_way_rows(self.rows)
        self.assertEqual(sw, [], "a SIXTH WAY exists — an op moves bytes but fits no family: %s"
                         % [(r["op"], r["reason"]) for r in sw])

    def test_no_unknown(self):
        # every op's source was read; an unreadable op would RED here rather than hide as
        # not-a-path (precision 2).
        uk = P4.unknown_rows(self.rows)
        self.assertEqual(uk, [], "an op's source could not be read: %s" % [r["op"] for r in uk])

    def test_every_family_is_populated(self):
        # the families are not empty categories — each has real members over the shipped registry
        # (design/52 §7 P4 premise). An empty family would mean the census proves nothing about it.
        for family in P4.FIVE_FAMILIES:
            self.assertTrue(P4.family_rows(self.rows, family),
                            "family %r has no members over the shipped registry" % family)


# ============================================================================================
# A2 — the live reading matches the committed evidence table (regenerated by --md only).
# ============================================================================================

class TestA2EvidencePin(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "planning/evidence/P4-FIVE-FAMILIES-CENSUS/five-families.md")),
        "SKIP PRIVATE-SOURCE: needs planning/evidence/P4-FIVE-FAMILIES-CENSUS/five-families.md (absent in the render)")
    def test_reading_matches_committed_evidence(self):
        _s, gate, views = P4.build_full_kernel_for_census()
        rows = P4.census(gate, views)
        generated = P4.render_markdown(rows)
        with open(P4.EVIDENCE_PATH, encoding="utf-8") as f:
            committed = f.read()
        self.assertEqual(
            generated.strip(), committed.strip(),
            "the five-families census reading diverged from the committed evidence table — an op "
            "was added or a reading changed. Regenerate (never hand-edit): "
            "python3 -m tools.conformance.five_families_census --md")


# ============================================================================================
# A3 — the check can fail: a planted byte-mover fitting no family reads as sixth-way.
# ============================================================================================

# A planted handler that moves bytes by a byte-transfer primitive (hand_off) — a real crossing —
# under an op NAME and LAW that match NO family. This is the shape the census exists to catch.
PLANT_SIXTH_WAY_SOURCE = '''\
def _sixth_way_plant(actor, params):
    # a real byte crossing (a content datum handed to a receiver) under no recognised conduit.
    hand_off([params["target_hash"]], params["receipt"])
    return {"actor": actor, "action": "SIXTH-WAY-PLANT", "object": params["target_hash"],
            "rule_cited": "NONE"}
'''


class TestA3PlantedSixthWayStatic(unittest.TestCase):

    def test_classifier_flags_a_byte_mover_with_no_family_as_sixth_way(self):
        # read the planted op directly: no definition (code-registered shape), a handler that
        # moves bytes, a name in no family -> sixth-way.
        row = P4.classify("SIXTH-WAY-PLANT", definition=None,
                          handler_src=PLANT_SIXTH_WAY_SOURCE, law="NONE")
        self.assertEqual(row["class"], "sixth-way",
                         "the classifier did not flag a byte-mover fitting no family — the census cannot fail")
        self.assertIn("across a boundary", row["reason"])

    def test_a_definition_born_byte_mover_with_no_family_is_a_sixth_way(self):
        # the other shape: a definition-born op carrying content_params to a target_param under a
        # name/law in no family -> sixth-way. (Not registered — no founding move; read directly.)
        plant_def = {"law_cited": "NONE", "content_params": {"payload": "payload_hash"},
                     "target_param": "receiver"}
        row = P4.classify("BEAM-CONTENT", definition=plant_def, handler_src=None, law="NONE")
        self.assertEqual(row["class"], "sixth-way")

    def test_a_real_family_member_is_not_flagged(self):
        # the control the other way: a real byte-mover that IS in a family (COMMS-SEND, channels)
        # is NOT a sixth way — the plant is discriminating, not a check that reds on everything.
        _s, gate, views = P4.build_full_kernel_for_census()
        rows = P4.census(gate, views)
        by_op = {r["op"]: r for r in rows}
        self.assertEqual(by_op["COMMS-SEND"]["class"], "channels")
        self.assertEqual(by_op["HANDOVER-CUSTODY"]["class"], "custody-handover")


class TestA3PlantedSixthWayBehavioural(unittest.TestCase):

    def _register_plant(self, gate):
        """Register (in memory, NOT a founding CREATE-OP) a byte-moving op that fits no family —
        the exact shape the census exists to catch. gate.register is a live registration, like the
        effect-order census's planted-inline control; nothing is written to the pack."""
        def _sixth_way_plant(actor, params):
            hand_off([params["target_hash"]], params["receipt"])          # noqa: F821 — planted crossing
            return {"actor": actor, "action": "SIXTH-WAY-PLANT",
                    "object": params["target_hash"], "rule_cited": "NONE"}
        gate.register("SIXTH-WAY-PLANT",
                      {"description": "planted byte-mover fitting no family",
                       "rules": [], "params": {"target_hash": "required", "receipt": "required"}},
                      _sixth_way_plant)

    def test_planted_op_reds_the_census_then_greens_on_removal(self):
        _s, gate, views = P4.build_full_kernel_for_census()

        # green before the plant
        self.assertEqual(P4.sixth_way_rows(P4.census(gate, views)), [])

        # THE POSITIVE FIRES: the plant is present and reads as a sixth way.
        self._register_plant(gate)
        rows = P4.census(gate, views)
        sw = [r["op"] for r in P4.sixth_way_rows(rows)]
        self.assertIn("SIXTH-WAY-PLANT", sw,
                      "the planted byte-mover was NOT flagged sixth-way — the positive control did "
                      "not fire, so this test proves nothing")
        self.assertEqual(len(rows), len(gate.ops))          # still complete WITH the plant

        # remove the plant: the census is green again — the finding class is kept, not defeated.
        gate.unregister("SIXTH-WAY-PLANT")
        self.assertEqual(P4.sixth_way_rows(P4.census(gate, views)), [])


if __name__ == "__main__":
    unittest.main()
