# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Kelvin Chau and AWIG OS contributors
#
# This file is part of AWIG OS.
# AWIG OS is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version. See the LICENSE file for details.
"""AWIG OS body — the derive-from-the-rows generator (C7 P3b-1; design/54 §7 P3b-1, §9).

An ATTESTED src member (§9 mechanism 1: ONE attested list). It reads the twelve
seam_act_definition rows from the founding pack and folds {seam_kind: label} through the
estate's ONE canonical serializer (kernel/boot._act_kind_digest, the same floor
kernel/boot.py:880 stands on and views/protection stand on) into the twelve rows' digest, then
emits src/body/rows_digest.h with that digest as a C constant.

WHAT IS DERIVED, HONESTLY (§9 mechanism 2): only this header (the digest constant + the act
count) is generated — the memory C (PMM/VMM/heap/serial/boot) is HAND-WRITTEN and read whole.
A PMM is not derivable from twelve act-kind rows; only the body's tie to its definition (the
digest) is. Two properties hold and are tested (A3):
  * a body generated from DIFFERENT rows emits a DIFFERENT digest (tied to its definition,
    archi :4001 precision b);
  * delete-and-regenerate returns byte-identical bytes (the owner's bar, carried to the body).

Run from the repo root:  PYTHONPATH=src python3 src/body/gen_rows_digest.py
"""

import json
import os
import pathlib
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_SRC = os.path.abspath(os.path.join(_HERE, os.pardir))
sys.path.insert(0, _SRC)

from kernel.boot import ACT_KIND_RECORD_KIND, _act_kind_digest  # noqa: E402
# C7 P2 seam law (host_crossing_census): this generator is core src/ code, so its file I/O routes
# through the host seam — the pack read like the installer's (install.load_pack) and the header write
# through host().write_bytes, never a direct builtin open(). No undeclared crossing above the seam.
from bridge.host_seam import host  # noqa: E402

PACK_PATH = os.path.join(_SRC, "founding", "founding-pack.json")
HEADER_PATH = os.path.join(_HERE, "rows_digest.h")


def rows_from_pack(pack):
    """Every seam_act_definition record anywhere in the pack — the same rows live_act_kinds folds
    (kernel/boot.py). Scans structurally rather than assuming a fixed nesting, so a pack whose
    steps are re-shaped still yields the rows."""
    rows = []

    def scan(node):
        if isinstance(node, dict):
            if node.get("kind") == ACT_KIND_RECORD_KIND:
                rows.append(node)
            for value in node.values():
                scan(value)
        elif isinstance(node, list):
            for value in node:
                scan(value)

    scan(pack)
    return rows


def digest_over(pack):
    """(digest, count) — the {seam_kind: label} fold through the estate's canonical serializer."""
    rows = rows_from_pack(pack)
    kind_to_label = {row["seam_kind"]: row["label"] for row in rows}
    return _act_kind_digest(kind_to_label), len(kind_to_label)


def render(digest, count):
    """The rows_digest.h bytes. Deterministic: same rows -> same bytes (delete-and-regenerate).

    The SPDX licence block is EMITTED here, as part of the generated output — a generated file's
    licence line is the generator's to write, never a hand stamp (RELEASE-4 round 2, board :4642).
    So delete-and-regenerate returns the committed bytes byte-for-byte, header included (B11)."""
    return (
        "/* SPDX-License-Identifier: GPL-3.0-or-later\n"
        " * gov-os freestanding body. Copyright (C) Kelvin Chau.\n"
        " * Licensed under the GNU General Public License, version 3 or later.\n"
        " * See LICENSE and LICENSING.md at the public repository root. */\n"
        "/* GENERATED by src/body/gen_rows_digest.py from the twelve seam_act_definition rows.\n"
        " * DO NOT EDIT BY HAND. delete-and-regenerate returns these exact bytes (A3, the owner's bar).\n"
        " * The digest folds {seam_kind: label} through the estate's ONE canonical serializer\n"
        " * (kernel/boot._act_kind_digest) and is byte-identical to _act_kind_digest driven in main. */\n"
        "#ifndef ROWS_DIGEST_H\n"
        "#define ROWS_DIGEST_H\n"
        '#define ROWS_DIGEST "' + digest + '"\n'
        "#define ROWS_ACT_COUNT " + str(count) + "\n"
        "#endif /* ROWS_DIGEST_H */\n"
    )


def generate(pack_path=PACK_PATH, header_path=HEADER_PATH):
    # read the pack + write the header THROUGH THE SEAM (C7 P2) — no direct builtin open().
    with host().open_read_text(pack_path, encoding="utf-8") as f:
        pack = json.load(f)
    digest, count = digest_over(pack)
    text = render(digest, count)
    host().write_bytes(pathlib.Path(header_path), text.encode("utf-8"))
    return digest, count, header_path


if __name__ == "__main__":
    d, n, path = generate()
    print("wrote %s: %s over %d rows" % (path, d, n))
