/* SPDX-License-Identifier: GPL-3.0-or-later
 * gov-os freestanding body. Copyright (C) Kelvin Chau.
 * Licensed under the GNU General Public License, version 3 or later.
 * See LICENSE and LICENSING.md at the public repository root. */
/* GENERATED by src/body/gen_rows_digest.py from the twelve seam_act_definition rows.
 * DO NOT EDIT BY HAND. delete-and-regenerate returns these exact bytes (A3, the owner's bar).
 * The digest folds {seam_kind: label} through the estate's ONE canonical serializer
 * (kernel/boot._act_kind_digest) and is byte-identical to _act_kind_digest driven in main. */
#ifndef ROWS_DIGEST_H
#define ROWS_DIGEST_H
#define ROWS_DIGEST "sha256:b16ee8a33d50424c8e4ed10474a3f2fed49f6693aa7b1b0492256d9ef842cfdb"
#define ROWS_ACT_COUNT 12
#endif /* ROWS_DIGEST_H */
